# This file is the todo list and who's job it will be to implement what
[lab_7.s]
main_routine="both"
move_player="nate"
end_game="nate"
pausing="nate"

[datastructures.s]
display_matrix="sebastien"
row_reflection="sebastien"
column_reflection="sebastien"

[rng.s]
create_seed="nate"
fill_board="nate"

[display.s]
main_menu="sebastien"
animations="sebastien"
draw_board="sebastien"
player_color_swap="sebastien"