# This file is the todo list and who's job it will be to implement what
[lab_7.s]
main_routine="both"
end_game="nate"
pausing="nate"

[datastructures.s]
display_matrix="sebastien"
row_reflection="sebastien"
column_reflection="sebastien"

[rng.s]
status="buggy"
fixrng="nate"

[display.s]
main_menu="sebastien"
animations="sebastien"
draw_board="sebastien"
player_color_swap="sebastien"

[LEDS]
reflect_color_on_leds="nate"

[debug]
cprogam="nate"
asmn="nate"

[documentation]
subroutineio="nate"
display="sebastien"
debug="nate"